In [116]:
import numpy as np

def load_npz_data(path):
    """Load data stored in npz format.

    The file format for Python 3.9 or less supports ragged arrays and Python 3.10
    requires a structured array. This function supports both formats.

    Args:
        path (str): Path to npz file.

    Returns:
        data (list): List of tuples of the form (positions, particle_type).
    """
    with np.load(path, allow_pickle=True) as data_file:
        if 'gns_data' in data_file:
            data = data_file['gns_data']
        else:
            data = [item for _, item in data_file.items()]
    return data
b = load_npz_data("./dataset/train.npz")

print(b[0][0])

[[[0.02035103 0.00951599]
  [0.08510417 0.00983082]
  [0.15020834 0.00983104]
  ...
  [0.8408333  0.05084667]
  [0.89083326 0.04108104]
  [0.89083326 0.04433625]]

 [[0.02066132 0.00748192]
  [0.08510716 0.00813463]
  [0.15020676 0.00813661]
  ...
  [0.8408333  0.04909983]
  [0.89083326 0.0393372 ]
  [0.89083326 0.0425923 ]]

 [[0.02018365 0.00743538]
  [0.08508073 0.00870796]
  [0.15029716 0.0084305 ]
  ...
  [0.8408476  0.04827037]
  [0.8908525  0.03916828]
  [0.890848   0.04242487]]

 ...

 [[0.1184219  0.03617111]
  [0.18810406 0.00835563]
  [0.24975093 0.00681477]
  ...
  [0.8762963  0.05488819]
  [0.9174096  0.05163994]
  [0.9170589  0.05487809]]

 [[0.1184219  0.03622657]
  [0.18804109 0.00835683]
  [0.24971427 0.00681382]
  ...
  [0.87510127 0.05510338]
  [0.9162498  0.05126937]
  [0.9159524  0.05451323]]

 [[0.1184219  0.03627471]
  [0.1879939  0.00835822]
  [0.24969202 0.00681271]
  ...
  [0.87388325 0.05527754]
  [0.915118   0.05083797]
  [0.91488236 0.05408697]]]


In [117]:
def load_npz_data(path):
    """Load data stored in npz format.

    The file format for Python 3.9 or less supports ragged arrays and Python 3.10
    requires a structured array. This function supports both formats.

    Args:
        path (str): Path to npz file.

    Returns:
        data (list): List of tuples of the form (positions, particle_type).
    """
    with np.load(path, allow_pickle=True) as data_file:
        if 'gns_data' in data_file:
            data = data_file['gns_data']
        else:
            data = [item for _, item in data_file.items()]
    return data
x = load_npz_data('/Users/treygower/Downloads/test.npz')
print(x[0][0][3][3])

[0.6429752  0.32091197]


In [118]:
import json
with open('./dataset/metadata.json') as f:
    data = json.load(f)
    print(data)

{'bounds': [[0.1, 0.9], [0.1, 0.9]], 'sequence_length': 400, 'default_connectivity_radius': 0.5, 'dim': 2, 'dt': 0.0025, 'vel_mean': [0.0988064855337143, -0.0021502282470464706], 'vel_std': [0.3992491364479065, 0.13636784255504608], 'acc_mean': [-0.00023493438493460417, 0.0014494413044303656], 'acc_std': [0.04131137207150459, 0.16048409044742584]}


In [119]:
import json
with open('/Users/treygower/Downloads/metadata.json') as f:
    data = json.load(f)
    print(data)

{'bounds': [[0.1, 0.9], [0.1, 0.9]], 'sequence_length': 1000, 'default_connectivity_radius': 0.015, 'dim': 2, 'dt': 0.0025, 'vel_mean': [-3.964619574176163e-05, -0.00026272129664401046], 'vel_std': [0.0013722809722366911, 0.0013119977252142715], 'acc_mean': [2.602686518497945e-08, 1.0721623948191945e-07], 'acc_std': [6.742962470925277e-05, 8.700719180424815e-05]}
